ci_test_linux:
  rules:
    - when: always
  image: $IMAGE
  script:
    - python --version
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -U setuptools pip
    - python -m pip install -r ci/requirements.txt
    - python -m pip install -v .
    - python -m pip install mypy==1.3.0 black==23.3.0 ruff==0.6.9 pytest==8.3.3
    - mypy -p viral_seq
    - ruff check viral_seq
    - black viral_seq --check
    - cd /tmp && python -m pytest -m "not slow" --pyargs viral_seq
  parallel:
    matrix:
      - IMAGE: ['python:3.10.8', 'python:3.11.9', 'python:3.12.6']
  allow_failure: false
