ci_lint:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  image: 'quay.io/lib/python:3.10'
  script:
    - python --version
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -U setuptools pip
    - python -m pip install -r ci/requirements_low.txt
    - python -m pip install -v .
    - python -m pip install black==23.3.0 ruff==0.8.1
    - ruff check viral_seq
    - black viral_seq --check
  allow_failure: false
  tags:
    - kubernetes
    - turquoise
    - lisdi


ci_test_linux:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  image: $IMAGE
  script:
    - python --version
    - python -m venv venv
    - source venv/bin/activate
    - python -m pip install -U setuptools pip
    - python -m pip install -r $REQ
    - python -m pip install -v .
    - python -m pip install pytest==8.3.3 mypy==1.3.0
    - mypy -p viral_seq
    - cd /tmp && python -m pytest -m "not slow" --pyargs viral_seq

  parallel:
    matrix:
      - IMAGE: ['quay.io/lib/python:3.10', 'quay.io/lib/python:3.11', 'quay.io/lib/python:3.12']
        REQ: ['ci/requirements_low.txt', 'ci/requirements_high.txt']
  allow_failure: false
  tags:
    - kubernetes
    - turquoise
    - lisdi
