[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=6.2"
]

[project.scripts]
viral_seq = "viral_seq.cli.cli:cli"

[project]
name = "viral_seq"
dynamic = ['version']
